version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: techassist-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TechAssist2024!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database/schema.sql:/tmp/schema.sql
    networks:
      - techassist-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P TechAssist2024! -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    command: >
      /bin/bash -c "
      echo '🚀 Iniciando SQL Server...' &&
      /opt/mssql/bin/sqlservr &
      echo '⏳ Esperando 60 segundos para que SQL Server inicie completamente...' &&
      sleep 60 &&
      echo '📊 Ejecutando script de inicialización...' &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P TechAssist2024! -i /tmp/schema.sql &&
      echo '✅ Base de datos TechAssistDB creada exitosamente' &&
      echo '✅ SQL Server listo para aceptar conexiones' &&
      wait
      "

  backend:
    build: ./backend
    container_name: techassist-backend
    ports:
      - "8001:8001"
    environment:
      - DB_SERVER=sqlserver
      - DB_NAME=TechAssistDB
      - DB_USER=sa
      - DB_PASSWORD=TechAssist2024!
      - DB_PORT=1433
      - SECRET_KEY=super-secret-key-change-in-production-min-32-chars-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - DEBUG=True
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8001
      - UPLOAD_FOLDER=/app/uploads
      - MAX_UPLOAD_SIZE=5242880
      - ALLOWED_EXTENSIONS=jpg,jpeg,png,gif,pdf
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - techassist-network
    restart: on-failure
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: techassist-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - techassist-network
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  techassist-network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
  backend_uploads:
    driver: local